export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_SUCCESS_TOPIC = 'REQUEST_SUCCESS_TOPIC';
export const REQUEST_SUCCESS_COMMENTS = 'REQUEST_SUCCESS_COMMENTS'
export const REQUEST_SUCCESS_BANKS = 'REQUEST_SUCCESS_BANKS';
export const REQUEST_SUCCESS_CITIES = 'REQUEST_SUCCESS_CITIES';
export const REQUEST_SUCCESS_RESTAURANTS = 'REQUEST_SUCCESS_RESTAURANTS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

export const CREATE_BANK_REQUEST = 'CREATE_BANK_REQUEST';
export const CREATE_BANK_FAILURE = 'CREATE_BANK_FAILURE';
export const CREATE_BANK_SUCCESS = 'CREATE_BANK_SUCCESS';
export const GET_BANKS = 'GET_BANKS';
export const GET_BANKS_REQUEST = 'GET_BANKS_REQUEST';
export const GET_BANKS_SUCCESS = 'GET_BANKS_SUCCESS';
export const GET_BANKS_FAILURE = 'GET_BANKS_FAILURE';
export const DESTROY_BANK = 'DESTROY_BANK';

export const CREATE_RESTAURANT_REQUEST = 'CREATE_RESTAURANT_REQUEST';
export const CREATE_RESTAURANT_FAILURE = 'CREATE_RESTAURANT_FAILURE';
export const CREATE_RESTAURANT_SUCCESS = 'CREATE_RESTAURANT_SUCCESS';
export const GET_RESTAURANTS = 'GET_RESTAURANTS';
export const GET_RESTAURANTS_REQUEST = 'GET_RESTAURANTS_REQUEST';
export const GET_RESTAURANTS_SUCCESS = 'GET_RESTAURANTS_SUCCESS';
export const GET_RESTAURANTS_FAILURE = 'GET_RESTAURANTS_FAILURE';
export const DESTROY_RESTAURANT = 'DESTROY_RESTAURANT';

export const DESTROY_CARD_FROM_BANK_FAILURE = 'DESTROY_CARD_FROM_BANK_FAILURE';
export const DESTROY_CARD_FROM_BANK = 'DESTROY_CARD_FROM_BANK';
export const DESTROY_CARD_FROM_BANK_SUCCESS = 'DESTROY_CARD_FROM_BANK_SUCCESS';
export const UPDATE_CARDS_FOR_BANK = 'UPDATE_CARDS_FOR_BANK';

export const CREATE_CITY_REQUEST = "CREATE_CITY_REQUEST"
export const DESTROY_CITY = "DESTROY_CITY"
export const CREATE_CITY_SUCCESS = "CREATE_CITY_SUCCESS"
export const CREATE_CITY_FAILURE = "CREATE_CITY_FAILURE"

export const CREATE_TOPIC_REQUEST = 'CREATE_TOPIC_REQUEST';
export const CREATE_TOPIC_FAILURE = 'CREATE_TOPIC_FAILURE';
export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
export const CREATE_TOPIC_DUPLICATE = 'CREATE_TOPIC_DUPLICATE';
export const GET_TOPICS = 'GET_TOPICS';
export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAILURE = 'GET_TOPICS_FAILURE';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const DESTROY_TOPIC = 'DESTROY_TOPIC';
export const TYPING = 'TYPING';

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';

export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const ADD_COMMENT = "ADD_NEW_COMMENT"
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS"
export const ADD_COMMENT_FAILURE = "ADD_COMMENT_FAILURE"
export const DELETE_COMMENT = "DELETE_NEW_COMMENT"
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS"
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE"
export const GET_COMMENTS = "GET_COMMENTS"
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS"
export const GET_COMMENTS_FAILURE = "GET_COMMENTS_FAILURE"
export const TYPING_COMMENT = 'TYPING_COMMENT'

